import Select from "react-select";
import type { SingleValue, StylesConfig } from "react-select";

type CountryOption = { value: string; label: string };

const COUNTRIES: CountryOption[] = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
].map((c) => ({ value: c, label: c }));

/** Matches `.zendt-input-surface` horizontal padding (px-4). */
const INPUT_PAD_X = 12;

function darkStylesFor(borderRadius: number): StylesConfig<CountryOption, false> {
  return {
    control: (base, state) => ({
      ...base,
      backgroundColor: "#1E1E1E",
      borderColor: state.isFocused ? "rgba(255,255,255,0.3)" : "rgba(255,255,255,0.1)",
      borderRadius,
      minHeight: 46,
      boxShadow: "none",
      "&:hover": { borderColor: "rgba(255,255,255,0.2)" },
    }),
    valueContainer: (base) => ({
      ...base,
      paddingLeft: INPUT_PAD_X,
      paddingRight: 8,
    }),
    menu: (base) => ({
      ...base,
      backgroundColor: "#1E1E1E",
      borderRadius,
      border: "1px solid rgba(255,255,255,0.1)",
      zIndex: 50,
    }),
    option: (base, state) => ({
      ...base,
      backgroundColor: state.isFocused ? "rgba(255,255,255,0.1)" : "transparent",
      color: "white",
      cursor: "pointer",
      fontSize: 14,
      padding: `10px ${INPUT_PAD_X}px`,
    }),
    singleValue: (base) => ({ ...base, color: "white", fontSize: 14 }),
    input: (base) => ({ ...base, color: "white", fontSize: 14 }),
    placeholder: (base) => ({ ...base, color: "rgba(255,255,255,0.4)", fontSize: 14 }),
    indicatorSeparator: () => ({ display: "none" }),
    dropdownIndicator: (base) => ({ ...base, color: "rgba(255,255,255,0.4)" }),
  };
}

type CountrySelectProps = {
  value: string;
  onChange: (value: string) => void;
  disabled?: boolean;
  placeholder?: string;
  /** `surface` matches `.zendt-input-surface`; `surface-10` matches `.zendt-input-surface-10`. */
  variant?: "surface" | "surface-10";
};

export default function CountrySelect({
  value,
  onChange,
  disabled = false,
  placeholder = "Search and select country",
  variant = "surface",
}: CountrySelectProps) {
  const selected = COUNTRIES.find((c) => c.value === value) || null;
  const borderRadius = variant === "surface-10" ? 10 : 11;

  return (
    <Select<CountryOption>
      options={COUNTRIES}
      value={selected}
      onChange={(opt: SingleValue<CountryOption>) => onChange(opt?.value || "")}
      placeholder={placeholder}
      isSearchable
      isDisabled={disabled}
      styles={darkStylesFor(borderRadius)}
      menuPlacement="auto"
    />
  );
}
